def modules():
	print("pi()")
	print("octo()\nattention prend un peu de temps ! ")
	print("namedcolorchart()")
	print("trace_triangle()")
	print("trace_triangle_SL()")
	print("trace_carre()")
	print("BlueShades()")
	print("donut()")
	print("Hurricane()")
	print("PurplePentagons()")
	print("SilverAngles()")
	print("SquareShell()")
	print("sunflower()")
	print("Windmil()")
	print("triangle_Sierpinsky()")
	print("etoile_sbpm()")
	print("courbeKoch()")

modules()